USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS streamlit_readonly_role;

CREATE USER IF NOT EXISTS streamlit_demo_user
  PASSWORD = 'RagCortex#78_Pw'
  DEFAULT_ROLE = streamlit_readonly_role
  DEFAULT_WAREHOUSE = CORTEX_SEARCH_TUTORIAL_WH
  MUST_CHANGE_PASSWORD = FALSE;

GRANT USAGE ON WAREHOUSE CORTEX_SEARCH_TUTORIAL_WH TO ROLE streamlit_readonly_role;

GRANT USAGE ON DATABASE CORTEX_SEARCH_TUTORIAL_DB TO ROLE streamlit_readonly_role;
GRANT USAGE ON SCHEMA CORTEX_SEARCH_TUTORIAL_DB.PUBLIC TO ROLE streamlit_readonly_role;

GRANT SELECT ON ALL TABLES IN SCHEMA CORTEX_SEARCH_TUTORIAL_DB.PUBLIC TO ROLE streamlit_readonly_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CORTEX_SEARCH_TUTORIAL_DB.PUBLIC TO ROLE streamlit_readonly_role;

GRANT USAGE ON CORTEX SEARCH SERVICE CORTEX_SEARCH_TUTORIAL_DB.PUBLIC.FOMC_SEARCH_SERVICE
  TO ROLE streamlit_readonly_role;

GRANT ROLE streamlit_readonly_role TO USER streamlit_demo_user;
